<a href="https://colab.research.google.com/github/SEC-API-io/sec-api-cookbook/blob/main/notebooks/csv-export/csv-export.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## How to Export SEC Filing Metadata to a CSV File

SEC EDGAR filing metadata, including the filer's CIK, ticker, URL to the filing content, filing date, form type, and other parameters, can be exported to a CSV file for analysis in different tools. This example demonstrates how to export SEC filing metadata to a CSV file using the `sec-api` library.

The Query API is used to retrieve SEC filings that match a specified search criteria, such as all filings from Microsoft in January 2024.

```
ticker:MSFT AND filedAt:[2024-01-01 TO 2024-01-31]
```

A `field_names` list is defined, with each entry representing a filing field and column to be saved to the CSV file. Pandas is used to create a DataFrame from the search results and export the data to a CSV file `filings.csv`.

In [ ]:
pip install sec-api

In [ ]:
from sec_api import QueryApi
import pandas as pd

queryApi = QueryApi(api_key="YOUR_API_KEY")

In [ ]:
search_parameters = {
    "query": "ticker:MSFT AND filedAt:[2024-01-01 TO 2024-03-31]",
    "from": "0",
    "size": "50",
    "sort": [{"filedAt": {"order": "desc"}}],
}

response = queryApi.get_filings(search_parameters)

In [ ]:
filings = pd.DataFrame(response["filings"])
print("Number of filings: ", len(filings))
filings.head(3)

Number of filings:  42

,ticker,formType,accessionNo,cik,companyNameLong,companyName,linkToFilingDetails,description,linkToTxt,filedAt,documentFormatFiles,periodOfReport,entities,id,seriesAndClassesContractsInformation,linkToHtml,linkToXbrl,dataFiles,items
0,MSFT,11-K,0000950170-24-034807,789019,MICROSOFT CORP (Filer),MICROSOFT CORP,https://www.sec.gov/Archives/edgar/data/789019...,Form 11-K - Annual report of employee stock pu...,https://www.sec.gov/Archives/edgar/data/789019...,2024-03-21T16:43:04-04:00,"[{'sequence': '1', 'size': '169301', 'document...",2023-12-31,"[{'fiscalYearEnd': '0630', 'stateOfIncorporati...",6bfec9c9284b22aaa31b585dfc2367e1,[],https://www.sec.gov/Archives/edgar/data/789019...,,[],NaN
1,MSFT,4,0001062993-24-006558,789019,MICROSOFT CORP (Issuer),MICROSOFT CORP,https://www.sec.gov/Archives/edgar/data/789019...,Form 4 - Statement of changes in beneficial ow...,https://www.sec.gov/Archives/edgar/data/789019...,2024-03-15T18:14:39-04:00,"[{'sequence': '1', 'size': ' ', 'documentUrl':...",2024-03-14,"[{'fiscalYearEnd': '0630', 'stateOfIncorporati...",97a378d6579c752fb2b8dc472895dbaf,[],https://www.sec.gov/Archives/edgar/data/789019...,,[],NaN
2,MSFT,4,0001062993-24-006557,789019,MICROSOFT CORP (Issuer),MICROSOFT CORP,https://www.sec.gov/Archives/edgar/data/789019...,Form 4 - Statement of changes in beneficial ow...,https://www.sec.gov/Archives/edgar/data/789019...,2024-03-15T18:14:13-04:00,"[{'sequence': '1', 'size': ' ', 'documentUrl':...",2024-03-14,"[{'fiscalYearEnd': '0630', 'stateOfIncorporati...",f214c7b6a44d43eda13f77d3c06e5570,[],https://www.sec.gov/Archives/edgar/data/789019...,,[],NaN

In [ ]:
# every entry in field_names represents a filing parameter
# and the column name in the CSV file
field_names = ["id", "accessionNo", "formType",
               "filedAt", "items",  "periodOfReport",
               "companyName", "cik", "ticker",
               "linkToFilingDetails", "linkToTxt",
               "documentFormatFiles", "dataFiles", "entities"]

# write the data to a CSV file
filings[field_names].to_csv('filings.csv', index=False)

In [ ]:
# read data from the CSV file
filings_from_csv = pd.read_csv('filings.csv')

print("Filing metadata of 10 most recent filings by Tesla saved to filings.csv:\n")
filings_from_csv.head(3)

Filing metadata of 10 most recent filings by Tesla saved to filings.csv:

,id,accessionNo,formType,filedAt,items,periodOfReport,companyName,cik,ticker,linkToFilingDetails,linkToTxt,documentFormatFiles,dataFiles,entities
0,6bfec9c9284b22aaa31b585dfc2367e1,0000950170-24-034807,11-K,2024-03-21T16:43:04-04:00,NaN,2023-12-31,MICROSOFT CORP,789019,MSFT,https://www.sec.gov/Archives/edgar/data/789019...,https://www.sec.gov/Archives/edgar/data/789019...,"[{'sequence': '1', 'size': '169301', 'document...",[],"[{'fiscalYearEnd': '0630', 'stateOfIncorporati..."
1,97a378d6579c752fb2b8dc472895dbaf,0001062993-24-006558,4,2024-03-15T18:14:39-04:00,NaN,2024-03-14,MICROSOFT CORP,789019,MSFT,https://www.sec.gov/Archives/edgar/data/789019...,https://www.sec.gov/Archives/edgar/data/789019...,"[{'sequence': '1', 'size': '\xa0', 'documentUr...",[],"[{'fiscalYearEnd': '0630', 'stateOfIncorporati..."
2,f214c7b6a44d43eda13f77d3c06e5570,0001062993-24-006557,4,2024-03-15T18:14:13-04:00,NaN,2024-03-14,MICROSOFT CORP,789019,MSFT,https://www.sec.gov/Archives/edgar/data/789019...,https://www.sec.gov/Archives/edgar/data/789019...,"[{'sequence': '1', 'size': '\xa0', 'documentUr...",[],"[{'fiscalYearEnd': '0630', 'stateOfIncorporati..."